Comisaria/CRUD/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/comisaria/', permanent=False)),

    path("comisaria/", include("Comisaria.urls")),
    path('admin/', admin.site.urls),
    
]

Comisaria/Comisaria/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.views.generic import RedirectView
urlpatterns = [
    #Index
    path( "inicio/", views.index, name="inicio"),
    path('', RedirectView.as_view(pattern_name='inicio', permanent=False)),
    #Listas en general
    path( "empleado/", views.EmpleadoView.as_view(), name="empleado"),
    path( "oficial/", views.OficialView.as_view(), name="oficial"),
    path( "caso/", views.CasoView.as_view(), name="caso"),
    path( "reporte/", views.ReporteServicioView.as_view(), name="reporte_servicio"),
    #Formularios De Creacion
    path( "empleado/crear", views.empleado_view, name="empleado_crear"),
    path( "oficial/crear", views.oficial_view, name="oficial_crear"),
    path( "caso/crear", views.caso_view, name="caso_crear"),
    path( "caso/<int:caso_id>/crear", views.reporte_caso_view, name="reporte_caso_crear"),
    path( "reporte/crear", views.reporte_servicio_view, name="reporte_servicio_crear"),
    #Campos De Elminar
    path( "empleado/eliminar/<int:id>", views.empleado_delete_view, name="empleado_eliminar"),
    path( "oficial/eliminar/<int:id>", views.oficial_delete_view, name="oficial_eliminar"),
    path( "caso/eliminar/<int:id>", views.caso_delete_view, name="caso_eliminar"),
    path( "caso/<int:caso_id>/eliminar/<int:id>", views.reporte_caso_delete_view, name="reporte_caso_eliminar"),
    path( "reporte/eliminar/<int:id>", views.reporte_servicio_delete_view, name="reporte_servicio_eliminar"),
    #Detalles de un campo
    path( "empleado/<int:pk>", views.EmpleadoDetallesView.as_view(), name="empleado_deta"),
    path( "oficial/<int:pk>", views.OficialDetallesView.as_view(), name="oficial_deta"),
    path( "caso/<int:pk>", views.CasoDetallesView.as_view(), name="caso_deta"),
    path( "caso/<int:caso_id>/<int:pk>", views.ReporteCasoDetallesView.as_view(), name="reporte_caso_deta"),
    path( "reporte/<int:pk>", views.ReporteServicioDetallesView.as_view(), name="reporte_servicio_deta"),
    #path( "reporte/<int:caso>", views.oficial_form, name="oficial"),
    #Editar campo
    path( "empleado/edit/<int:pk>", views.EmpleadoUpdate.as_view(), name="empleado_edit"),
    path( "oficial/edit/<int:pk>", views.OficialUpdate.as_view(), name="oficial_edit"),
    path( "caso/edit/<int:pk>", views.CasoUpdate.as_view(), name="caso_edit"),
    path( "caso/<int:caso_id>/edit/<int:pk>", views.ReporteCasoUpdate.as_view(), name="reporte_caso_edit"),
    path( "reporte/edit/<int:pk>", views.ReporteServicioUpdate.as_view(), name="reporte_servicio_edit"),
    #Login//logout
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    
]

Comisaria/Comisaria/models.py
from django.db import models
from django.utils import timezone
import uuid
import random
from django.contrib.auth.models import User
from django.db.models.signals import post_save

from django.contrib.auth.models import AbstractUser

class Empleado(AbstractUser):
    class Puesto(models.IntegerChoices):
        ADMINISTRATIVO = 1, "Personal Administrativo"
        INTELIGENCIA = 2, "Analistas de Inteligencia"
        FORENSE = 3, "Técnico Forense"
        ARCHIVO = 4, "Personal del Archivo"
        COMUNICACION = 5, "Operador de Comunicación"
        PSICOLOGIA = 6, "Psicólogos"
        MANTENIMIENTO = 7, "Personal de Mantenimiento"
        HUMANOS = 8, "Encargado de Recursos Humanos"
        TI = 9, "Tecnicos de Sistemas Informaticos"
        OFICIAL = 10, "Oficial"
    first_name = models.CharField(max_length=50, default='', blank=False, verbose_name='Nombre(s)')
    last_name = models.CharField(max_length=50, default='', blank=False, verbose_name='Apellido paterno')
    last_name2 = models.CharField(max_length=50, default='', blank=False, verbose_name='Apellido materno')
    email = models.EmailField(unique=True, verbose_name='Correo')
    puesto = models.IntegerField(choices=Puesto.choices, default=Puesto.ADMINISTRATIVO, verbose_name='Puesto')
    register_date = models.DateTimeField(default= timezone.now, null=True, blank=False, verbose_name='Fecha de registro')
    num_phone = models.CharField(max_length=14, default='', blank=False, verbose_name='Telefono')
    salario = models.DecimalField(max_digits=10, decimal_places=2, default=0.00,blank=False ,verbose_name='Salario')
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
    def save(self, *args, **kwargs):
        if (self.username== None or self.username==""):
            self.username = "{}{}{}".format(self.first_name.split()[0] if self.first_name.strip() else "", 
                                            self.last_name.split()[0] if self.first_name.strip() else "",
                                            ''.join(map(str, random.sample(range(10), 4)))
                                            )
        super().save(*args, **kwargs)




class oficiales(models.Model):
    class Rango(models.IntegerChoices):
        POLICIA = 1, "Policía"
        INSPECTOR = 2, "Inspector"
        COMISARIO = 3, "Comisario"
    num_placa = models.PositiveIntegerField(default=0,blank=True, verbose_name='Numero de placa')
    id_emp = models.OneToOneField(Empleado, on_delete=models.CASCADE, verbose_name='ID empleado')
    rank = models.IntegerField(choices=Rango.choices, default=Rango.POLICIA, verbose_name='Rango')
    def __str__(self):
        return f'{self.num_placa}'
    class Meta:
        verbose_name = 'Oficial'
        verbose_name_plural = 'Oficiales'
    def save(self, *args, **kwargs):
        if (self.num_placa== None or self.num_placa==0):
            self.num_placa = "{}".format(''.join(map(str, random.sample(range(10), 5))))
        super().save(*args, **kwargs)


class reportes_de_servicio(models.Model):
    class Tipo(models.IntegerChoices):
        PATRULLAJE = 1, "Patrullaje"
        INCIDENTE = 2, "Incidente"
        ARRESTO = 3, "Arresto"
        TRAFICO = 4, "Tráfico o colisión"
        DIARIA = 5, "Actividad diaria"
    titulo = models.CharField(max_length=50, verbose_name='Titulo')
    contenido = models.TextField(verbose_name='Contenido')
    num_placa = models.ForeignKey(oficiales, on_delete=models.CASCADE, verbose_name='Oficial')
    tipo = models.IntegerField(choices=Tipo.choices, default=Tipo.DIARIA, verbose_name='Tipo de reporte')
    fecha = models.DateField(auto_now=False, verbose_name='Fecha de Reporte')
    class Meta:
        verbose_name = 'Reporte de servicio'
        verbose_name_plural = 'Reportes de servicio'
    def __str__(self):
        return f'{self.titulo}'
    

class registro_casos(models.Model):
    class Estatus(models.IntegerChoices):
        ABIERTO = 1, "Abierto"
        CERRADO = 2, "Cerrado"
    titulo = models.CharField(max_length=50, verbose_name='Titulo')
    descripcion = models.TextField(verbose_name='Descripcion')
    num_placa = models.ForeignKey(oficiales, on_delete=models.CASCADE, verbose_name='Designado')
    estatus = models.IntegerField(choices=Estatus.choices, default=Estatus.ABIERTO, verbose_name='Estatus')
    fecha_inicio = models.DateField(auto_now=False, verbose_name='Fecha de Regsitro')
    fecha_fin = models.DateField(auto_now=False , null=True, blank=True, verbose_name='Fecha de cerrado')
    class Meta:
        verbose_name = 'Registro de caso'
        verbose_name_plural = 'Registros de Casos'
    def __str__(self):
        return f'{self.titulo} {self.estatus}'

class reportes_caso(models.Model):
    class Tipo(models.IntegerChoices):
        INICIAL = 1, "Investigacion inicial"
        ENTREVISTA = 2, "Entrevista o Interrogatorio"
        EVIDENCIA = 3, "Evidencias"
        PERICIAL = 4, "Pericial forense"
        INTELIGENCIA = 5, "De inteligencia"
        VIGILANCIA = 6, "Observación o vigilancia"
    id_caso= models.ForeignKey(registro_casos, on_delete=models.CASCADE, verbose_name='Caso')
    fecha_reporte = models.DateTimeField(verbose_name='Fecha de reporte')
    titulo = models.CharField(max_length=50, verbose_name='Titulo')
    contenido = models.TextField(verbose_name='Contenido')
    tipo = models.IntegerField(choices=Tipo.choices, default=Tipo.INICIAL, verbose_name='Tipo de reporte')
    class Meta:
        verbose_name = 'Reporte de caso'
        verbose_name_plural = 'Reportes de casos'

    def __str__(self):
        return f'{self.titulo} {self.tipo}'


    

Comisaria/Comisaria/views/caso.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import UpdateView
from ..models import registro_casos
from ..forms import CasoUpdateForm, CasosDetailForm, CasosForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

#READ
class CasoView(generic.ListView):
    template_name = "comisaria/READ/caso.html"
    context_object_name ="casos"
    def get_queryset(self):
        return registro_casos.objects.order_by("titulo")[:5]
    
#EDIT
class CasoUpdate(UpdateView):
    model = registro_casos
    form_class = CasoUpdateForm
    template_name = 'comisaria/forms/form.html'
    success_url = reverse_lazy('caso')

#DETALLES
class CasoDetallesView(generic.DetailView):
    model = registro_casos
    template_name = "comisaria/DETALLES/detallesCaso.html"
    context_object_name = 'caso'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CasosDetailForm(instance=self.object)
        return context
#FORMS Creacion
@login_required
def caso_view(request):
    if request.method == "POST":
        form = CasosForm(request.POST)
        print(form.data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("caso"))
        else:
            return render(request, 'comisaria/forms/form.html', {'form': form})
    form = CasosForm()
    return render(request, 'comisaria/forms/form.html', {'form': form})

#ELIMINAR
def caso_delete_view(request, id):
    entidad = get_object_or_404(registro_casos, pk = id)
    entidad.delete()
    return HttpResponseRedirect(reverse('caso'))

Comisaria/Comisaria/views/empleado.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from ..models import Empleado
from ..forms import EmpleadoUpdateForm, EmpleadoDetailForm, CustomUserCreationForm
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

#READ
class EmpleadoView(generic.ListView):
    template_name = "comisaria/READ/empleado.html"
    context_object_name ="empleados"
    def get_queryset(self):
        return Empleado.objects.order_by("first_name")[:5]
    
#EDIT
class EmpleadoUpdate(UpdateView):
    model = Empleado
    form_class = EmpleadoUpdateForm
    template_name = 'comisaria/forms/form.html'
    success_url = reverse_lazy('empleado')

#DETALLES
class EmpleadoDetallesView(generic.DetailView):
    model = Empleado
    template_name = "comisaria/DETALLES/detalles.html"
    context_object_name="empleado"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = EmpleadoDetailForm(instance=self.object)
        return context
    
#FORMS Creacion
@login_required
def empleado_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        print(form.data)
        if form.is_valid():
            form.save()
            if(request.POST["puesto"]==10):
                return HttpResponseRedirect(reverse("oficial_crear"))
            else:
                return HttpResponseRedirect(reverse("empleado"))
        else:
            return render(request, 'comisaria/forms/form.html', {'form': form})
    form = CustomUserCreationForm()
    return render(request, 'comisaria/forms/form.html', {'form': form})

#ELIMINAR
def empleado_delete_view(request, id):
    entidad = get_object_or_404(Empleado, pk = id)
    entidad.delete()
    return HttpResponseRedirect(reverse('empleado'))

Comisaria/Comisaria/views/mainPage.py
#READ
from django.shortcuts import render


def index(request):
    return render(request, 'comisaria/index.html')

Comisaria/Comisaria/views/oficial.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from ..models import oficiales
from ..forms import OficialesForm, OficialesUpdateForm, OficialDetailForm
from django.views.generic.edit import UpdateView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

#READ
class OficialView(generic.ListView):
    template_name = "comisaria/READ/oficial.html"
    context_object_name ="oficiales"
    def get_queryset(self):
        return oficiales.objects.order_by("num_placa")[:5]

#EDIT
class OficialUpdate(UpdateView):
    model = oficiales
    form_class = OficialesUpdateForm
    template_name = 'comisaria/forms/form.html'
    success_url = reverse_lazy('oficial')

#DETALLES
class OficialDetallesView(generic.DetailView):
    model = oficiales
    template_name = "comisaria/DETALLES/detalles.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = OficialDetailForm(instance=self.object)
        return context

#FORMS Creacion
@login_required
def oficial_view(request):
    if request.method == "POST":
        form = OficialesForm(request.POST)
        print(form.data)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("oficial"))
        else:
            return render(request, 'comisaria/forms/form.html', {'form': form})
    form = OficialesForm()
    return render(request, 'comisaria/forms/form.html', {'form': form})

#ELIMINAR
def oficial_delete_view(request, id):
    entidad = get_object_or_404(oficiales, pk = id)
    entidad.delete()
    return HttpResponseRedirect(reverse('oficial'))

Comisaria/Comisaria/views/repoCaso.py
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import UpdateView
from ..models import registro_casos, reportes_caso
from ..forms import ReporteCasoForm, ReporteCasoUpdateForm, ReporteCasoDetailForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

#READ
class ReporteCasoView(generic.ListView):
    template_name = "comisaria/READ/reportecaso.html"
    context_object_name ="reportes"
    def get_queryset(self):
        return reportes_caso.objects.order_by("titulo")[:5]
#EDIT
class ReporteCasoUpdate(UpdateView):
    model = reportes_caso
    form_class = ReporteCasoUpdateForm
    template_name = 'comisaria/forms/form.html'
    success_url = reverse_lazy('caso')

#DETALLES
class ReporteCasoDetallesView(generic.DetailView):
    model = reportes_caso
    template_name = "comisaria/DETALLES/detalles.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Instanciar el formulario con la instancia del producto
        context['form'] = ReporteCasoDetailForm(instance=self.object)
        return context
    
#FORMS Creacion
@login_required
def reporte_caso_view(request, caso_id):
    if request.method == "POST":
        form = ReporteCasoForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.id_caso = get_object_or_404(registro_casos, pk = caso_id)
            form.save()
            return HttpResponseRedirect(reverse('caso_deta', kwargs={'pk': caso_id}))
        else:
            return render(request, 'comisaria/forms/form.html', {'form': form})
    form = ReporteCasoForm()
    return render(request, 'comisaria/forms/form.html', {'form': form})

#ELIMINAR
def reporte_caso_delete_view(request,caso_id, id):
    entidad = get_object_or_404(reportes_caso, pk = id)
    entidad.delete()
    return HttpResponseRedirect(reverse('caso_deta', kwargs={'pk': caso_id}))

Comisaria/Comisaria/templates/comisaria/READ/caso.html
{% extends 'comisaria/base.html' %}

{%block titulo %} Casos {% endblock %}

{% block contenido %}
<div class="d-flex justify-content-end mb-3">
    <a class="btn btn-success" href="{% url 'caso_crear' %}">Agregar Caso</a>
</div>
    {% if casos %}
    <div class="container my-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre clave</th>
                    <th>Numero de placa</th>
                    <th>Estatus</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for caso in casos %}
                <tr>
                    <td>{{ caso.titulo }}</td>
                    <td>{{ caso.num_placa.num_placa }}</td>
                    <td>{{ caso.get_estatus_display }}</td>
                    <td><a class="btn btn-primary btn-sm" href="{% url 'caso_deta' caso.id %}">Ver</a> | 
                        <a class="btn btn-warning btn-sm" href="{% url 'caso_edit' caso.id  %}">Editar</a> | 
                        <a class="btn btn-danger btn-sm" href="{% url 'caso_eliminar' caso.id  %}">Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Sin casos que mostrar</p>
    {% endif %}
    {% if message_error %}
    <p>Formulario Invalido</p>
    {% endif %}

{% endblock %}

Comisaria/Comisaria/templates/comisaria/READ/empleado.html
{% extends 'comisaria/base.html' %}

{%block titulo %} Empleados {% endblock %}

{% block contenido %}
    {% if empleados %}
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-success" href="{% url 'empleado_crear' %}">Agregar Empleado</a>
    </div>
   <div class="container my-5">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Username</th>
                <th>Nombre(s)</th>
                <th>Apellido Paterno</th>
                <th>Puesto</th>
                <th>Salario</th>
                <th>Editar</th>
            </tr>
        </thead>
        <tbody>
            {% for emp in empleados %}
            <tr>
                <td>{{ emp.username }}</td>
                <td>{{ emp.first_name }}</td>
                <td>{{ emp.last_name }}</td>
                <td>{{ emp.get_puesto_display }}</td>
                <td>{{ emp.salario }}</td>
                <td><a class="btn btn-primary btn-sm" href="{% url 'empleado_deta' emp.id %}">Ver</a> | <a class="btn btn-warning btn-sm" href="{% url 'empleado_edit' emp.id %}">Editar</a> | <a class="btn btn-danger btn-sm" href="{% url 'empleado_eliminar' emp.id  %}">Eliminar</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
   </div>
    {% else %}
    <p>Sin empleados que mostrar</p>
    {% endif %}

{% endblock %}

Comisaria/Comisaria/templates/comisaria/READ/oficial.html
{% extends 'comisaria/base.html' %}

{%block titulo %} Oficiales {% endblock %}

{% block contenido %}
<div class="d-flex justify-content-end mb-3">
    <a class="btn btn-success" href="{% url 'oficial_crear' %}">Agregar Oficial</a>
</div>
    {% if oficiales %}
    <div class="container my-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Numero de placa</th>
                    <th>Nombre(s)</th>
                    <th>Apellido Paterno</th>
                    <th>Rango</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for of in oficiales %}
                <tr>
                    <td>{{ of.num_placa }}</td>
                    <td>{{ of.id_emp.first_name }}</td>
                    <td>{{ of.id_emp.last_name }}</td>
                    <td>{{ of.get_rank_display }}</td>
                    <td><a class="btn btn-primary btn-sm" href="{% url 'oficial_deta' of.id %}">Ver</a> | <a class="btn btn-warning btn-sm" href="{% url 'oficial_edit' of.id%}">Editar</a> | <a class="btn btn-danger btn-sm" href="{% url 'oficial_eliminar' of.id  %}">Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Sin oficiales que mostrar</p>
    {% endif %}

{% endblock %}

Comisaria/Comisaria/templates/comisaria/READ/reporteServicio.html
{% extends 'comisaria/base.html' %}

{%block titulo %} Reportes de Casos {% endblock %}

{% block contenido %}
<div class="d-flex justify-content-end mb-3">
    <a class="btn btn-success" href="{% url 'reporte_servicio_crear' %}">Agregar Reporte de Servicio</a>
</div>
    {% if reportes %}
    <div class="container my-5">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Titulo</th>
                    <th>Designado</th>
                    <th>tipo</th>
                    <th>Editar</th>
                </tr>
            </thead>
            <tbody>
                {% for reporte in reportes %}
                <tr>
                    <td>{{ reporte.titulo }}</td>
                    <td>{{ reporte.num_placa }}</td>
                    <td>{{ reporte.get_tipo_display }}</td>
                    <td><a class="btn btn-primary btn-sm" href="{% url 'reporte_servicio_deta' reporte.id %}">Ver</a> | <a class="btn btn-warning btn-sm" href="{% url 'reporte_servicio_edit' reporte.id %}">Editar</a> | <a class="btn btn-danger btn-sm" href="{% url 'reporte_servicio_eliminar' reporte.id  %}">Eliminar</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
    <p>Sin reportes de servicio que mostrar</p>
    {% endif %}

{% endblock %}